### ISSUE TITLE
Remove unneeded dependencies before release

### ISSUE THREAD

**Issue by tfachmann** [tfachmann/typst-as-library#5]
Before #3, remove unneeded dependencies such as

```toml
# typst rendering (for demonstration purpose)
typst-pdf = "0.11.0"
typst-svg = "0.11.0"
```

so the boilerplate (library code) is independent of the examples-

Related to #1
